import {Inter} from "next/font/google";

import {Logo} from "@/components";

import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 z-20 w-full bg-background/50 backdrop-blur-sm">
          <nav className="mx-auto flex h-16 max-w-screen-standar items-center justify-between gap-2 pl-[max(env(safe-area-inset-left),1.5rem)] pr-[max(env(safe-area-inset-right),1.5rem)]">
            <Logo height={35} />
            <ul className="text-lg">Navigation List For The Page</ul>
          </nav>
        </header>
        <main className="mx-auto grid w-full max-w-screen-standar flex-1 pl-[max(env(safe-area-inset-left),1.5rem)] pr-[max(env(safe-area-inset-right),1.5rem)]">
          {children}
        </main>
        {/* <footer className="relative pb-[env(safe-area-inset-bottom)]">
          <div className="mx-auto flex max-w-screen-standar justify-center py-6 pl-[max(env(safe-area-inset-left),1.5rem)] pr-[max(env(safe-area-inset-right),1.5rem)]">
            Made with ❤️ by WiFo
          </div>
        </footer> */}
      </body>
    </html>
  );
}
